package com.ang.test.employeetracker.controller;

import com.ang.test.employeetracker.model.Department;
import com.ang.test.employeetracker.model.Employee;
import com.ang.test.employeetracker.repo.DepartmentRepository;
import com.ang.test.employeetracker.repo.EmployeeRepository;
import io.swagger.annotations.Api;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Api(tags="Department API", description="manage Department information")
@Controller // This means that this class is a Controller
@RequestMapping(path="/department") // This means URL's start with /demo (after Application path)
public class DepartmentController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private DepartmentRepository departmentRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewDepartment (@RequestParam String name) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Department n = new Department();
        n.setName(name);
        departmentRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Department> getAllUsers() {
        // This returns a JSON or XML with the users
        return departmentRepository.findAll();
    }
}
